### ISSUE TITLE
Multiple Plotly in a page

### ISSUE THREAD

**Issue by vitroid** [aknakos/sveltekit-plotly#2]
Is it possible to put two independent plotly panel in a same page?
As far as I tested, only the first one is accessible.

**Comment by christinoleo** [comment]
Yes, I use several without issues. Do you mean something like the image below?
What kind of problem are you seeing?

![image](https://user-images.githubusercontent.com/1745901/211903040-1c7b3b0a-b54f-4dfe-a761-1d887c07f1e3.png)

**Comment by vitroid** [comment]
Thank you for quick reply. I found it was my mistake. It works well.

**Comment by christinoleo** [comment]
Nice! I'm glad to hear it! :)

**Comment by aryadaroui** [comment]
I found that each instance activated the

```svelte
<svelte:head>
	<script src="https://cdn.plot.ly/plotly-latest.min.js" on:load={init} on:error={handleLoadingError}></script>
</svelte:head>
```

which added the script to the app `<head>` and triggered another download of Plotly from the CDN.

I got around it by loading Plotly in a global `+layout.svelte` for my app, and then calling your `init()` function there.

Maybe it was how I implemented it though
